// ==========================================================================
// Copyright (C) 2018 - 2021 Beijing 51WORLD Digital Twin Technology Co., Ltd. 
// , and/or its licensors.  All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related 
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Beijing 51WORLD Digital Twin Technology Co., Ltd. 
// ("51WORLD") and/or its licensors,  which is protected by the People's 
// Republic of China and/or other countries copyright law and by 
// international treaties.
//
// The Data may not be disclosed or distributed to third parties or be
// copied or duplicated, in whole or in part, without the prior written
// consent of 51WORLD.
//
// The copyright notices in the Software and this entire statement,
// including the above license grant, this restriction and the following
// disclaimer, must be included in all copies of the Software, in whole
// or in part, and all derivative works of the Software, unless such copies
// or derivative works are solely in the form of machine-executable object
// code generated by a source language processor.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
// 51WORLD DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED
// WARRANTIES INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF
// NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE,
// OR ARISING FROM A COURSE OF DEALING, USAGE, OR TRADE PRACTICE. IN NO
// EVENT WILL 51WORLD AND/OR ITS LICENSORS BE LIABLE FOR ANY LOST
// REVENUES, DATA, OR PROFITS, OR SPECIAL, DIRECT, INDIRECT, OR
// CONSEQUENTIAL DAMAGES, EVEN IF 51WORLD AND/OR ITS LICENSORS HAS
// BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.
// ==========================================================================
#pragma once

#include "libexport.h"

#ifdef STATIC_SSD
#include "SSD/public/SimString.h"
#else
#include "SSD/SimString.h"
#endif
#include "public/MProtoDataStruct.h"

#if defined(WIN32) || defined(_WIN32)
  #define HDMAP_WIN 1
#else
  #define HDMAP_LINUX 1
#endif


#if HDMAP_WIN
  namespace rt {
    namespace hdmap
    {
        class Lane;
        class Crosswalk;
        class Stopline;
        class ParkingSpace;
        enum Lane_LaneType;
    }
}
#else
  namespace rt {
    namespace hdmap
    {
        class Lane;
        class Crosswalk;
        class Stopline;
        class ParkingSpace;
        enum Lane_LaneType : int;
    }
}
#endif

namespace HDMapStandalone {
    class LIBEXPORT MHDMapProto {
    public:
        //@brief Get lane's sample point info.
        //@param laneName with this format roadId_sectionIndex_laneId.
        //@pre-condition laneName must exist in current map. Please use API MHDMap::ContainsLane().
        //@return Returns ProtoLaneInfo object.
        static ProtoLaneInfo GetLaneSample(const SSD::SimString& laneName);

        //@brief Get traffic lights that are in logic bound with the specified lane.
        //@param laneName with this format roadId_sectionIndex_laneId.
        //@pre-condition laneName must exist in current map. Please use API MHDMap::ContainsLane().
        //@return Returns MSignalVector object.
        static SSD::SimVector<rt::hdmap::Signal> GetTrafficLights(const SSD::SimString& laneName);

        //@brief Get traffic light by id.
        //@param id is traffic light's id.
        //@pre-condition id must exist in current map.
        //@return Returns the reference to a rt::hdmap::Signal object.
        static const rt::hdmap::Signal& GetTrafficLight(const SSD::SimString& id);

        //@brief Get lane according to laneName.
        //@param laneName with this format roadId_sectionIndex_laneId.
        //@pre-condition laneName must exist in current map. Please use API MHDMap::ContainsLane().
        //@return Returns Lane object.
        static const rt::hdmap::Lane& GetLane(const SSD::SimString& laneName);

        //@brief Get lane's type according to laneName.
        //@param laneName with this format roadId_sectionIndex_laneId.
        //@pre-condition laneName must exist in current map. Please use API MHDMap::ContainsLane().
        //@return Returns Lane_LaneType object.
        static const rt::hdmap::Lane_LaneType& GetLaneType(const SSD::SimString& laneName);

        //@brief Get crosswalk according to object id.
        //@param crosswalk's object id.
        //@pre-condition id must exist in current map.
        //@return Returns Crosswalk object.
        static const rt::hdmap::Crosswalk& GetCrosswalk(const SSD::SimString& id);

        //@brief Get stopLine according to object id.
        //@param stopLine's object id.
        //@pre-condition id must exist in current map.
        //@return Returns Stopline object.
        static const rt::hdmap::Stopline& GetStopline(const SSD::SimString& id);

        //@brief Get parkingSpace according to object id.
        //@param parkingSpace's object id.
        //@pre-condition id must exist in current map.
        //@return Returns ParkingSpace object.
        static const rt::hdmap::ParkingSpace& GetParkingSpace(const SSD::SimString& id);
    };
}
