// ==========================================================================
// Copyright (C) 2018 - 2021 Beijing 51WORLD Digital Twin Technology Co., Ltd. 
// , and/or its licensors.  All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related 
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Beijing 51WORLD Digital Twin Technology Co., Ltd. 
// ("51WORLD") and/or its licensors,  which is protected by the People's 
// Republic of China and/or other countries copyright law and by 
// international treaties.
//
// The Data may not be disclosed or distributed to third parties or be
// copied or duplicated, in whole or in part, without the prior written
// consent of 51WORLD.
//
// The copyright notices in the Software and this entire statement,
// including the above license grant, this restriction and the following
// disclaimer, must be included in all copies of the Software, in whole
// or in part, and all derivative works of the Software, unless such copies
// or derivative works are solely in the form of machine-executable object
// code generated by a source language processor.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
// 51WORLD DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED
// WARRANTIES INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF
// NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE,
// OR ARISING FROM A COURSE OF DEALING, USAGE, OR TRADE PRACTICE. IN NO
// EVENT WILL 51WORLD AND/OR ITS LICENSORS BE LIABLE FOR ANY LOST
// REVENUES, DATA, OR PROFITS, OR SPECIAL, DIRECT, INDIRECT, OR
// CONSEQUENTIAL DAMAGES, EVEN IF 51WORLD AND/OR ITS LICENSORS HAS
// BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.
// ==========================================================================
#pragma once

#include "libexport.h"
#include "public/common/MEnum.h"
#include "public/threadSafe/MMapTS.h"
#include "public/threadSafe/MLocationTS.h"
#include "public/threadSafe/MLightAndSignTS.h"
#include "public/threadSafe/MRoutingTS.h"
#include "public/threadSafe/MNavigationTS.h"
#include "public/threadSafe/MV2XTS.h"

namespace HDMapStandalone {

	// In this system, laneName is organized as string(SSD::SimString) with this format roadId_sectionIndex_laneId.
	// In public/common/MLaneId.h, MLaneId class is defined to hold this format laneName as data struct.
	// Its method ToString() can convert MLaneId object into roadId_sectionIndex_laneId format string.

	class LIBEXPORT MHDMapTS
	{
	public:

		//@brief Constructor. It will load xodr data immediately. Map data can from  xodr file or xodr content.
		//map data's geographic info must be localENU.
		//If geographic info is not localENU, need to use Wet.exe or WorldEditor to convert xodr into our localENU format.
		//@param xodrFileOrContent represents the xodr file's pathname or xodr content.
		//sourceType represents XodrSourcType for loading data.
		MHDMapTS(const SSD::SimString& xodrFileOrContent, MXodrSourceType sourceType);

		//@brief Constructor. It will load xodr data from database.
		//map data's geographic info must be localENU.
		//If geographic info is not localENU, need to use Wet.exe or WorldEditor to convert xodr into our localENU format.
		//@param dbContent represents the json formatted content string.
		//headerXml represents the header info in xml format.
		MHDMapTS(const SSD::SimString& dbContent, const SSD::SimString& headerXml);

		//@brief Destructor.
		~MHDMapTS();

		//@brief Check whether xodr map is loaded. If failed, return load error code.
		//@param is as an output parameter, which returns load error code.
		//@return Returns true if already loaded with success, false if failed.
		bool IsMapLoaded(MLoadErrorCode& errorCode) const;

		//@brief Get MMapTS class object, so as to access more api.
		//@return Returns reference to MMapTS object.
		const MMapTS& GetMap() const;
		
		void* GetMapTSImp() const {
			return mImp;
		};

		//@brief Get MLocationTS class object, so as to access more api.
		//@return Returns reference to MLocationTS object.
		const MLocationTS& GetLocation() const;

		//@brief Get MLightAndSignTS class object, so as to access more api.
		//@return Returns reference to MLightAndSignTS object.
		const MLightAndSignTS& GetLightAndSign() const;

		//@brief Get MRoutingTS class object, so as to access more api.
		//@return Returns reference to MRoutingTS object.
		const MRoutingTS& GetRouting() const;

		//@brief Get MNavigationTS class object, so as to access more api.
		//@return Returns reference to MNavigationTS object.
		const MNavigationTS& GetNavigation() const;

	private:
		void* mImp = nullptr;
		MMapTS mMap;
		MLocationTS mLocation;
		MLightAndSignTS mLightAndSign;
		MRoutingTS mRouting;
		MNavigationTS mNavigation;
		MV2XTS mV2X;
		bool mbLoaded = false;
		MLoadErrorCode mError;

		friend class MMapTS;
		friend class MLocationTS;
		friend class MLightAndSignTS;
		friend class MRoutingTS;
		friend class MNavigationTS;
		friend class MV2XTS;
	};
}